baseURL = "https://meadon.net/"
title = "Tom Meadon"
languageCode = "en"
DefaultContentLanguage = "en"
theme = "loveit"
summarylength = 10
enableEmoji = true
enableRobotsTXT = true
canonifyURLs = true
pygmentsCodeFences = true
pygmentsUseClasses = true

# Enable Disqus
#disqusShortname = ""

# Google Analytics
googleAnalytics = "UA-179786144-1"

[params]
# title = "TOM MEADON"
# author = "Tom Meadon"
# description = "Technical Architect | Developer"
# profilePicture = "images/profile.jpg"
# keywords = ""
# favicon = "/"
# customCss = ["css/custom.css", "css/syntax-native.css", "css/syntax-manni.css"]
# customJs = []
# mainSections = ["posts"]
# images = ["images/site-feature-image.png"]
# copyright = '<a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'
# pygmentsCodeFences = true
# pygmentsUseClasses = true
# Google Site Verification
#googleSiteVerify = "ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789"
  version = "0.2.X"
  description = "Technical Architect | Developer"
  keywords = [ "blog" ]
  defaultTheme = "auto"
  dateFormat = "2006-01-02"
  images = ["/images/profile.jpg"]
  summaryLength = 100

  [params.app]
    title = "Tom Meadon"
    # noFavicon = false
    # svgFavicon = "" 
    themeColor = "#ffffff" # Android browser theme color
    iconColor = "#5bbad5" # Safari mask icon color
    tileColor = "#da532c" # Windows v8-10 tile color

  [params.search]
    enable = true
    # type of search engine ("lunr", "algolia")
    type = "lunr"
    # max index length of the chunked content
    contentLength = 4000
    # placeholder of the search bar
    placeholder = ""
    # max number of results length
    maxResultLength = 10
    # snippet length of the result
    snippetLength = 30
    # HTML tag name of the highlight part in results
    highlightTag = "em"
    # whether to use the absolute URL based on the baseURL in search index
    absoluteURL = false

  [params.header]
    # desktop header mode ("fixed", "normal", "auto")
    desktopMode = "fixed"
    # mobile header mode ("fixed", "normal", "auto")
    mobileMode = "auto"
    # Header title config
    [params.header.title]
      # URL of the LOGO
      logo = ""
      # title name
      name = "Tom Meadon"
      # you can add extra information before the name (HTML format is supported), such as icons
      pre = ""
      # you can add extra information after the name (HTML format is supported), such as icons
      post = ""
      # LoveIt NEW | 0.2.5 whether to use typeit animation for title name
      typeit = false

  [params.footer]
    enable = true
    # Custom content (HTML format is supported)
    custom = ''
    # whether to show Hugo and theme info
    hugo = true
    # whether to show copyright info
    copyright = true
    # whether to show the author
    author = true
    # Site creation time
    since = 2019
    # ICP info only in China (HTML format is supported)
    icp = ""
    # license info (HTML format is supported)
    license = '<a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'

  [params.section]
    # special amount of posts in each section page
    paginate = 20
    # date format (month and day)
    dateFormat = "01-02"
    # amount of RSS pages
    rss = 10

  [params.list]
    # special amount of posts in each list page
    paginate = 20
    # date format (month and day)
    dateFormat = "01-02"
    # amount of RSS pages
    rss = 1

  [params.home]
    # amount of RSS pages
    rss = 10
    # Home page profile
    [params.home.profile]
      enable = true
      # Gravatar Email for preferred avatar in home page
      gravatarEmail = ""
      # URL of avatar shown in home page
      avatarURL = "/images/profile.png"
      # title shown in home page (HTML format is supported)
      title = "Tom Meadon"
      # subtitle shown in home page
      subtitle = "Technical Architect | Developer"
      # whether to use typeit animation for subtitle
      typeit = true
      # whether to show social links
      social = true
      # disclaimer (HTML format is supported)
      disclaimer = ""
    # Home page posts
    [params.home.posts]
      enable = true
      # special amount of posts in each home posts page
      paginate = 6

    [params.social]
    GitHub = "tmeadon"
    Linkedin = "tom-meadon-1052a7a6"
    Twitter = "tommagumma"
    Instagram = "tom_meadon"
    Email = "blog@meadon.me"

    [params.page]
      # whether to hide a page from home page
      hiddenFromHomePage = false
      # whether to hide a page from search results
      hiddenFromSearch = false
      # whether to enable twemoji
      twemoji = false
      # whether to enable lightgallery
      lightgallery = false
      # whether to enable the ruby extended syntax
      ruby = true
      # whether to enable the fraction extended syntax
      fraction = true
      # whether to enable the fontawesome extended syntax
      fontawesome = true
      # whether to show link to Raw Markdown content of the content
      linkToMarkdown = true
      # whether to show the full text content in RSS
      rssFullText = false
      # Table of the contents config
      [params.page.toc]
        # whether to enable the table of the contents
        enable = true
        # whether to keep the static table of the contents in front of the post
        keepStatic = false
        # whether to make the table of the contents in the sidebar automatically collapsed
        auto = true
      # KaTeX mathematical formulas
      [params.page.math]
        enable = true
        # default block delimiter is $$ ... $$ and \\[ ... \\]
        blockLeftDelimiter = ""
        blockRightDelimiter = ""
        # default inline delimiter is $ ... $ and \\( ... \\)
        inlineLeftDelimiter = ""
        inlineRightDelimiter = ""
        # KaTeX extension copy_tex
        copyTex = true
        # KaTeX extension mhchem
        mhchem = true
      # Code config
      [params.page.code]
        # whether to show the copy button of the code block
        copy = true
        # the maximum number of lines of displayed code by default
        maxShownLines = -1
      # Mapbox GL JS config
      [params.page.mapbox]
        # access token of Mapbox GL JS
        accessToken = ""
        # style for the light theme
        lightStyle = "mapbox://styles/mapbox/light-v9"
        # style for the dark theme
        darkStyle = "mapbox://styles/mapbox/dark-v9"
        # whether to add NavigationControl
        navigation = true
        # whether to add GeolocateControl
        geolocate = true
        # whether to add ScaleControl
        scale = true
        # whether to add FullscreenControl
        fullscreen = true
      # social share links in post page
      [params.page.share]
        enable = true
        Twitter = true
        Facebook = true
        Linkedin = false
        Whatsapp = true
        Pinterest = false
        Tumblr = false
        HackerNews = false
        Reddit = false
        VK = false
        Buffer = false
        Xing = false
        Line = true
        Instapaper = false
        Pocket = false
        Digg = false
        Stumbleupon = false
        Flipboard = false
        Weibo = true
        Renren = false
        Myspace = true
        Blogger = true
        Baidu = false
        Odnoklassniki = false
        Evernote = true
        Skype = false
        Trello = false
        Mix = false

    [params.typeit]
    # typing speed between each step (measured in milliseconds)
    speed = 100
    # blinking speed of the cursor (measured in milliseconds)
    cursorSpeed = 1000
    # character used for the cursor (HTML format is supported)
    cursorChar = "|"
    # cursor duration after typing finishing (measured in milliseconds, "-1" means unlimited)
    duration = -1

  # LoveIt NEW | 0.2.10 Site SEO config
  [params.seo]
    # image URL
    image = ""
    # thumbnail URL
    thumbnailUrl = ""

  # LoveIt NEW | 0.2.0 Analytics config
  [params.analytics]
    enable = true
    # Google Analytics
    [params.analytics.google]
      id = "G-H94LKW1XWJ"
      # whether to anonymize IP
      anonymizeIP = true
    # Fathom Analytics
    [params.analytics.fathom]
      id = ""
      # server url for your tracker if you're self hosting
      server = ""

  # LoveIt CHANGED | 0.2.7 CDN config for third-party library files
  [params.cdn]
    # CDN data file name, disabled by default
    # ("jsdelivr.yml")
    # located in "themes/LoveIt/assets/data/cdn/" directory
    # you can store your own data files in the same path under your project:
    # "assets/data/cdn/"
    data = ""

  # LoveIt NEW | 0.2.8 Compatibility config
  [params.compatibility]
    # whether to use Polyfill.io to be compatible with older browsers
    polyfill = false
    # whether to use object-fit-images to be compatible with older browsers
    objectFit = false

# Markup related config in Hugo
[markup]
  # Syntax Highlighting
  [markup.highlight]
    codeFences = true
    guessSyntax = true
    lineNos = true
    lineNumbersInTable = true
    # false is a necessary configuration
    # (https://github.com/dillonzq/LoveIt/issues/158)
    noClasses = false
  # Goldmark is from Hugo 0.60 the default library used for Markdown
  [markup.goldmark]
    [markup.goldmark.extensions]
      definitionList = true
      footnote = true
      linkify = true
      strikethrough = true
      table = true
      taskList = true
      typographer = true
    [markup.goldmark.renderer]
      # whether to use HTML tags directly in the document
      unsafe = true
  # Table Of Contents settings
  [markup.tableOfContents]
    startLevel = 2
    endLevel = 6

# Author config
[author]
  name = "Tom Meadon"
  email = ""
  link = "https://blog.meadon.me"

# Sitemap config
[sitemap]
  changefreq = "weekly"
  filename = "sitemap.xml"
  priority = 0.5

# Permalinks config
[Permalinks]
  # posts = ":year/:month/:filename"
  posts = ":filename"

# Privacy config
[privacy]
  # LoveIt DELETED | 0.2.0 privacy of the Google Analytics (replaced by params.analytics.google)
  [privacy.googleAnalytics]
    # ...
  [privacy.twitter]
    enableDNT = true
  [privacy.youtube]
    privacyEnhanced = true

# Options to make output .md files
[mediaTypes]
  [mediaTypes."text/plain"]
    suffixes = ["md"]

# Options to make output .md files
[outputFormats.MarkDown]
  mediaType = "text/plain"
  isPlainText = true
  isHTML = false

# Options to make hugo output files
[outputs]
  # LoveIt CHANGED | 0.2.0
  home = ["HTML", "RSS", "JSON"]
  page = ["HTML", "MarkDown"]
  section = ["HTML", "RSS"]
  taxonomy = ["HTML", "RSS"]
  taxonomyTerm = ["HTML"]

## Math settings
[params.math]
enable = true  # options: true, false. Enable math support globally, default: false. You can always enable math on per page.
use = "katex"  # options: "katex", "mathjax". default is "katex".

[taxonomies]
category = "categories"
tag      = "tags"
series   = "series"

## Social links
[[params.socialIcons]]
icon = "fa-linkedin"
title = "Linkedin"
url = "https://www.linkedin.com/in/tom-meadon-1052a7a6/"

[[params.socialIcons]]
icon = "fa-github"
title = "GitHub"
url = "https://github.com/tmeadon"

[[params.socialIcons]]
icon = "fa-twitter"
title = "twitter"
url = "https://twitter.com/tommagumma"

[[params.socialIcons]]
icon = "fa-envelope"
title = "e-mail"
url = "mailto:blog@meadon.me"

## Menu items

[menu]

  [[menu.main]]
  name = "Home"
  identifier = "home"
  weight = 100
  url = "/"

  [[menu.main]]
  name = "Posts"
  weight = 200
  identifier = "posts"
  url = "/posts/"

  [[menu.main]]
  name = "About"
  weight = 300
  identifier = "about"
  url = "/about/"
