baseURL = "https://blog.meadon.me/"
languageCode = "en"
DefaultContentLanguage = "en"
theme = "anatole"
summarylength = 10
enableEmoji = true
enableRobotsTXT = true
pygmentsCodeFences = true
pygmentsUseClasses = true

# Enable Disqus
#disqusShortname = ""

# Google Analytics
googleAnalytics = "UA-179786144-1"

[params]
title = "TOM MEADON"
author = "Tom Meadon"
description = "Technical Architect | Developer"
profilePicture = "images/profile.jpg"
keywords = ""
favicon = "favicons/"
customCss = ["css/custom.css", "css/syntax-solarizeddark.css"]
customJs = []
mainSections = ["posts"]
images = ["images/site-feature-image.png"]
# pygmentsCodeFences = true
# pygmentsUseClasses = true
# Google Site Verification
#googleSiteVerify = "ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789"

## Math settings
[params.math]
enable = true  # options: true, false. Enable math support globally, default: false. You can always enable math on per page.
use = "katex"  # options: "katex", "mathjax". default is "katex".

## Social links
[[params.socialIcons]]
icon = "fa-linkedin"
title = "Linkedin"
url = "https://www.linkedin.com/in/tom-meadon-1052a7a6/"

[[params.socialIcons]]
icon = "fa-github"
title = "GitHub"
url = "https://github.com/tommagumma"

[[params.socialIcons]]
icon = "fa-twitter"
title = "twitter"
url = "https://twitter.com/tommagumma"

[[params.socialIcons]]
icon = "fa-envelope"
title = "e-mail"
url = "mailto:blog@meadon.me"

## Menu items

[menu]

  [[menu.main]]
  name = "Home"
  identifier = "home"
  weight = 100
  url = "/"

  [[menu.main]]
  name = "Posts"
  weight = 200
  identifier = "posts"
  url = "/posts/"

  [[menu.main]]
  name = "About"
  weight = 300
  identifier = "about"
  url = "/about/"

