name: blog

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
        fetch-depth: 0

    - name: Hugo Setup
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: '0.75.1'

    - name: Hugo build
      run: hugo -s ./blog
      
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: published-blog
        path: ./blog/public

  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
        fetch-depth: 0

    - name: Azure PowerShell login
      uses: azure/login@v1.1
      with:
        creds: ${{secrets.AZURE_CREDS}}
        enable-AzPSSession: true 

    - name: Azure create resource group
      uses: azure/powershell@v1
      with:
        inlineScript: |
          $rgName = "blog"
          if (-not (Get-AzResourceGroup -ResourceGroupName $rgName -ErrorAction SilentlyContinue))
          {
            New-AzResourceGroup -ResourceGroupName $rgName -Location uksouth
          }
        azPSVersion: '3.1.0'

    - name: Azure ARM deployment
      uses: azure/arm-deploy@v1
      with:
        subscriptionId: ${{secrets.AZURE_SUB_ID}}
        resourceGroupName: blog
        template: ./deploy/blog/blog.deploy.json
