name: blog

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
        fetch-depth: 0

    - name: Hugo Setup
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: '0.75.1'

    - name: Hugo build
      run: hugo -s ./blog
      
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: published-blog
        path: ./blog/public

  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
        fetch-depth: 0

    - name: Download published blog
      uses: actions/download-artifact@v2
      with:
        name: published-blog
        path: deploy/blog/site

    - name: Azure PowerShell login
      uses: azure/login@v1.1
      with:
        creds: ${{secrets.AZURE_CREDS}}
        enable-AzPSSession: true 

    - name: Run Azure deployment script
      uses: azure/powershell@v1
      with:
        inlineScript: |
          & ./deploy/blog/deploy.ps1
        azPSVersion: '3.1.0'

