name: blog

on: [push]

jobs:
  stage:
    uses: tmeadon/meadon.me/.github/workflows/blog-deploy.yml@main
    with:
      siteBaseUrl: https://blogmeadonmestg.z33.web.core.windows.net/
      storageContainerUri: https://blogmeadonmestg.blob.core.windows.net/$web/
      environment: stage
    secrets:
      storageSasToken: ${{ secrets.BLOG_SAS_TOKEN }}
    
  prod:
    needs: [stage]
    uses: tmeadon/meadon.me/.github/workflows/blog-deploy.yml@main
    with:
      siteBaseUrl: https://blog.meadon.me/
      storageContainerUri: https://blogmeadonme.blob.core.windows.net/$web/
      environment: prod
    secrets:
      storageSasToken: ${{ secrets.BLOG_SAS_TOKEN }}
