name: blog

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
        fetch-depth: 0

    - name: Hugo Setup
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: '0.75.1'

    - name: Hugo build
      run: hugo -s ./blog
      
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: published-blog
        path: ./blog/public

  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Terraform Init
      uses: hashicorp/terraform-github-actions@master
      with:
        tf_actions_version: 0.12.13
        tf_actions_subcommand: "init"
        tf_actions_working_dir: "./deploy/blog"
        tf_actions_comment: true

    - name: "Terraform Validate"
      uses: hashicorp/terraform-github-actions@master
      with:
        tf_actions_version: 0.12.13
        tf_actions_subcommand: "validate"
        tf_actions_working_dir: "./deploy/blog"
        tf_actions_comment: true

    - name: "Terraform Plan"
      uses: hashicorp/terraform-github-actions@master
      with:
        tf_actions_version: 0.12.13
        tf_actions_subcommand: "plan"
        tf_actions_working_dir: "./deploy/blog"
        tf_actions_comment: true
      env:
        TF_VAR_agent_client_id: ${{ secrets.AZURE_CLIENT_ID }}
        TF_VAR_agent_client_secret: ${{ secrets.AZURE_CLIENT_SECRET }}
        TF_VAR_subscription_id: ${{ secrets.AZURE_SUB_ID }}
        TF_VAR_tenant_id: ${{ secrets.AZURE_TENANT_ID }