name: blog

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
        fetch-depth: 0

    - name: Hugo Setup
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: '0.85.0'
        extended: true

    - name: Hugo build
      run: hugo -s ./blog

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: blog
        path: ./blog/public

  stage:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: stage
      url: https://blogmeadonmestg.z33.web.core.windows.net/
    steps:

    - name: Download artifact
      uses: actions/download-artifact@v2
      with:
        name: blog
        path: ./blog

    - name: Copy to storage
      env:
        AZURE_STORAGE_URI: https://blogmeadonmestg.blob.core.windows.net/$web/
        AZURE_STORAGE_SAS: ${{ secrets.BLOG_SAS_TOKEN }}
      run: |
        azcopy10 sync ./blog/ "${AZURE_STORAGE_URI}${AZURE_STORAGE_SAS}" --delete-destination=true

  prod:
    runs-on: ubuntu-latest
    needs: stage
    environment:
      name: prod
      url: https://blog.meadon.me
    steps:

    - name: Download artifact
      uses: actions/download-artifact@v2
      with:
        name: blog
        path: ./blog

    - name: Copy to storage
      env:
        AZURE_STORAGE_URI: https://blogmeadonme.blob.core.windows.net/$web/
        AZURE_STORAGE_SAS: ${{ secrets.BLOG_SAS_TOKEN }}
      run: |
        azcopy10 sync ./blog/ "${AZURE_STORAGE_URI}${AZURE_STORAGE_SAS}" --delete-destination=true

