name: build_and_deploy

on: 
  workflow_call:
    inputs:
      siteBaseUrl:
        type: string
        required: true
      storageContainerUri:
        type: string
        required: true
      environment:
        type: string
        required: true
    secrets:
      storageSasToken:
        required: true

jobs:
  build_deploy:
    name: Build and deploy
    runs-on: ubuntu-latest
    environment:
      name: ${{ inputs.environment }}
      url: ${{ inputs.siteBaseUrl }}
    steps:
      - name: Checkout your repository using git
        uses: actions/checkout@v4
      
      - name: actions/setup-node@v4
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build -- --site ${{ inputs.siteBaseUrl }}

      - name: Copy to storage
        env:
          AZURE_STORAGE_URI: ${{ inputs.storageContainerUri }}
          AZURE_STORAGE_SAS: ${{ secrets.storageSasToken }}
        run: |
          azcopy10 sync ./dist "${AZURE_STORAGE_URI}${AZURE_STORAGE_SAS}" --delete-destination=true