name: Build and deploy

on:
  push:
    branches:
      - next

jobs:
  staging:
    name: Staging
    uses: tmeadon/meadon.me/.github/workflows/build_template.yml@next
    with:
      siteBaseUrl: https://blogmeadonmestg.z33.web.core.windows.net/
      storageContainerUri: https://blogmeadonmestg.blob.core.windows.net/$web/
      environment: stage
    secrets:
      storageSasToken: ${{ secrets.BLOG_SAS_TOKEN }}
