name: Build and deploy

on:
  push:
    branches:
      - next

jobs:
  staging:
    runs-on: ubuntu-latest
    environment:
      name: stage
      url: https://blogmeadonmestg.z33.web.core.windows.net
    steps:
      - name: Checkout your repository using git
        uses: actions/checkout@v4
      
      - name: actions/setup-node@v4
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build -- --site https://blogmeadonmestg.z33.web.core.windows.net          

      - name: Copy to storage
        env:
          AZURE_STORAGE_URI: https://blogmeadonmestg.blob.core.windows.net/$web/
          AZURE_STORAGE_SAS: ${{ secrets.BLOG_SAS_TOKEN }}
        run: |
          azcopy sync ./dist "${AZURE_STORAGE_URI}${AZURE_STORAGE_SAS}" --delete-destination=true
      
