name: Build and deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  staging:
    name: Staging
    uses: tmeadon/meadon.me/.github/workflows/build_template.yml@main
    with:
      siteBaseUrl: https://blogmeadonmestg.z33.web.core.windows.net/
      storageContainerUri: https://blogmeadonmestg.blob.core.windows.net/$web/
      environment: stage
    secrets:
      storageSasToken: ${{ secrets.STAGING_SAS_TOKEN }}

  prod:
    name: Production
    needs: [staging]
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    uses: tmeadon/meadon.me/.github/workflows/build_template.yml@main
    with:
      siteBaseUrl: https://meadon.net/
      storageContainerUri: https://blogmeadonme.blob.core.windows.net/$web/
      environment: prod
    secrets:
      storageSasToken: ${{ secrets.PROD_SAS_TOKEN }}
